const List<String> symptoms = [
  'Silna potrzeba wypicia z tendencją do natychmiastowego zrealizowania', 
  'Uczucie monotonii', 
  'Uczucie ssania w źołądku',
  'Uczucie braku czegoś', 
  'Sny alkoholowe', 
  'Suchy kac', 
  'Smak, zapach alkoholu gdy go nie ma', 
  'Stany depresyjne', 
  'Lęk', 
  'Ucuczie stałego napięcia i rozdrażnienia',
  'Pogorszenie pamięci i koncentracji',
  'Dokuczający stres', 
  'Natrętne myśli o alkoholu',
  'Przypomnienie sobie przyjemnego stanu po alkoholu',
  'Apatia, zobojętnienie', 
  'Ból', 
  'Znudzenie', 
  'Zwiększona liczba konfliktów',
  'Nadpobudliwość',
  'Zwątpienie w wartość trzeźwego życia',
  'Zaburzenia snu',
  'Skoki napięcia',
  'Rozpamiętywanie, rozzalenie', 
  'Powątpiewanie w terapię', 
  'Porównywanie się do innych',
  'Przeźywanie swojego źycia jako chronicznie frustrującego', 
  'Euforia'
];